### ISSUE TITLE
some issues i found after using it for a week 

### ISSUE THREAD

**Issue by harshpreets63** [Bartis1313/csgo#61] opened 2023-02-17 16:34 UTC
1st - Crashes if Injected in game, works fine if injected in lobby 
2nd - I was playing community server and found 1 player was missing from player list (cheat) and for him neither esp was working nor aimbot (only chams was working on him)
3rd- on latest commit aimbot doesn't work perfectly, recoil goes uncontrollable and aim goes quite high from the player.(works fine on older commits)

**Comment by Bartis1313** [comment] 2023-02-17 17:49
1st was pretty random, debugger used to end up callstack on materialsys. Is this happening everytime?
2nd very weird, chams worked because they don't need cache'er for ents.
3rd I tried to mess with aimbot to match couple of player fields but it's worse than any useful.

Some things I may update at this weekend.

**Comment by harshpreets63** [comment] 2023-02-17 17:53
> e things I may update this weekend.

Yes, it crashes 99% of the time if injected into the game. 
will wait for the update, Hoping to try it as soon as possible.

**Comment by Bartis1313** [comment] 2023-03-07 13:36
aimbot, rcs are now less shitty. RCS won't work as no recoil, slight assist.
Cache unchanged, it's UB to see this. I reproduced and nothing like that happened, if you see this often, add couple of logs to cache statements like reading ents name, checking the addr etc...
Random crashing, yes it happens quite rarely but does. There are 2 reasons, one that datamap sometimes reads up free'd ptr, other is materialsys.

**Comment by Bartis1313** [comment] 2023-04-07 07:36
Sorry for no updates, I have fixed the crashing, and worked on no events solutions to work with online mode. As well as many other pretty tricky stuff.
For reader: Something wrong is in game threads, fixing this only for material system will cost you only nerves. To safely init materials / textures the easiest solution is to find / create them in game threads. 
Expect the update today

**Comment by Bartis1313** [comment] 2023-04-07 20:33
closing with note that I am going to refactor the aimbot, as explained in project tab.

**Closed by Bartis1313** 2023-04-07 20:33 UTC
Labels: bug
