### ISSUE TITLE
cant build, so many files are missing 

### ISSUE THREAD

**Issue by harshpreets63** [Bartis1313/csgo#58] opened 2023-01-23 22:20 UTC
I cant build it as so many files are missing, like lazy_importer.hpp, imgui.h, discord*.hpp, magic_enum.hpp, xorstr.hpp, nlohman/JSON

**Comment by Bartis1313** [comment] 2023-01-24 02:20
Please [read](https://github.com/Bartis1313/csgo#instalation), this project uses package manager which should install your missing dependencies.
Install vcpkg, integrate it, clean solution, rebuild, violla your dependecies are installed. It should start the build output by printing cmakes infos, and all vcpkg related stuff.
You don't include libraries by your [own](https://github.com/Bartis1313/csgo/blob/master/hack/deps/README.md)

**Comment by harshpreets63** [comment] 2023-01-24 08:44
> Please [read](https://github.com/Bartis1313/csgo#instalation), this project uses package manager which should install your missing dependencies. Install vcpkg, integrate it, clean solution, rebuild, violla your dependecies are installed. It should start the build output by printing cmakes infos, and all vcpkg related stuff. You don't include libraries by your [own](https://github.com/Bartis1313/csgo/blob/master/hack/deps/README.md)

after installing vcpkg and integrating it with vs 
getting this error 
![image](https://user-images.githubusercontent.com/19235185/214247130-a15dab86-49bb-42a4-92ba-61ad10b7c61b.png)

**Comment by harshpreets63** [comment] 2023-01-24 09:30
Crashes latest Csgo on Injection

**Comment by Bartis1313** [comment] 2023-01-24 10:46
I have a quick poor solution, will push in few mins. The problem is harder to say for now than I thought, code with release does weird thing with ebp reg.

**Comment by Bartis1313** [comment] 2023-01-24 11:07
yes, that should fix the release building. As well as injection, although to fix it for stable non UB release build with every feature working fine, I need some time. Don't use release now if that's possible :/

**Comment by harshpreets63** [comment] 2023-01-24 11:28
> yes, that should fix the release building. As well as injection, although to fix it for stable non UB release build with every feature working fine, I need some time. Don't use release now if that's possible :/

Thanks for your work, buddy. Everything is working perfectly now. Just UI is messed up, it becomes quite difficult to choose drop-down options as they are not visible.

**Comment by Bartis1313** [comment] 2023-01-24 11:41
For now key handler widget doesn't work, will fix it today. Popups can be replaced with several window childs, UI is done just to be, matter of huge free time when anyone wants to make it as "nice-looking"

**Comment by Bartis1313** [comment] 2023-01-24 23:18
will fix this week with release builds UB, closing

**Closed by Bartis1313** 2023-01-24 23:18 UTC
